name: React build # Workflow 이름
# Event 감지
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# main branch에서 push 이벤트가 일어났을 때만 실행

jobs: # Job 설정
  build:
    runs-on: ubuntu-latest # Job 가상환경 인스턴스
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://allaboutour.co.kr
