name: React build
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Install dependencies
        run: yarn install

      - name: Build 
        run: yarn build
